package com.slokam.av.entity;

public enum MovieMediaType {
    POSTER, THEATRICAL_POSTER, FIRST_LOOK_POSTER, CHARACTER_POSTER, STILL, BEHIND_THE_SCENES_PHOTO, EVENT_PHOTO, OTHER_IMAGE, MOTION_POSTER, TEASER, TRAILER, TRAILER_VERSION, BEHIND_THE_SCENES, MAKING_OF, INTERVIEW, EVENT_VIDEO, PROMOTIONAL_VIDEO, OTHER;

    public boolean isPoster() { return this == POSTER || this == THEATRICAL_POSTER || this == FIRST_LOOK_POSTER || this == CHARACTER_POSTER; }
    public boolean isVideo() { return switch (this) { case MOTION_POSTER, TEASER, TRAILER, TRAILER_VERSION, BEHIND_THE_SCENES, MAKING_OF, INTERVIEW, EVENT_VIDEO, PROMOTIONAL_VIDEO -> true; default -> false; }; }
}
